# Generated by Django 2.2.6 on 2019-10-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category', to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='subcategory', to='products.SubCategory'),
        ),
    ]
