# Generated by Django 2.2.6 on 2019-10-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191005_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.SubCategory'),
        ),
    ]
